@echo off
echo Подключение к PostgreSQL...
psql -U postgres -d nebulahunt_dev -c "DELETE FROM admins WHERE id NOT IN (SELECT MIN(id) FROM admins WHERE email = 'tatyanamixx@gmail.com' AND role = 'SUPERVISOR' GROUP BY email);"
echo.
echo Создание уникального индекса...
psql -U postgres -d nebulahunt_dev -c "CREATE UNIQUE INDEX IF NOT EXISTS admins_email_unique ON admins(email);"
echo.
echo Проверка результата...
psql -U postgres -d nebulahunt_dev -c "SELECT id, email, role, is_2fa_enabled, name FROM admins WHERE email = 'tatyanamixx@gmail.com' AND role = 'SUPERVISOR';"
echo.
echo Нажмите любую клавишу для продолжения...
pause 